name: End-to-end Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'End-to-end Tests'

jobs:
  ios:
    name: iOS
    runs-on: ios-e2e-group
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          check-latest: true
      - name: Install package dependencies
        run: yarn
      - name: Build mobile dependencies
        run: yarn build --scope @celo/mobile --include-filtered-dependencies
      - name: Install Ruby dependencies
        run: |
          cd packages/mobile
          bundle install
      - name: Install CocoaPods dependencies
        run: |
          cd packages/mobile/ios
          bundle exec pod install
      - name: Run E2E tests
        run: |
          cd packages/mobile
          yarn run detox build-framework-cache
          yarn run test:e2e:ios -w 2
      - name: 'Upload E2E Artifacts'
        uses: actions/upload-artifact@v2
        with:
          path: packages/mobile/e2e/artifacts
      - name: 'Upload E2E Test Results'
        uses: actions/upload-artifact@v2
        with:
          path: packages/mobile/e2e/test-results
  android:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          check-latest: true
      - run: |
          echo 'export ANDROID_SDK_ROOT=$HOME/android-tools' >> $GITHUB_ENV
          echo 'export ANDROID_NDK=$ANDROID_SDK_ROOT/ndk/21.0.6113669' >> $GITHUB_ENV
      - run: |
          sh packages/mobile/scripts/install-android-tools.sh
          echo 'export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH' >> $GITHUB_ENV
          echo 'export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest:$PATH' >> $GITHUB_ENV
          echo 'export PATH=$ANDROID_SDK_ROOT/platform-tools:$PATH' >> $GITHUB_ENV
          echo 'export PATH=$ANDROID_SDK_ROOT/emulator:$PATH' >> $GITHUB_ENV
          source $GITHUB_ENV
          sdkmanager --list
      - run: avdmanager create avd --force --name Pixel_API_29_AOSP_x86_64 --package "system-images;android-29;default;x86_64" --device pixel
      - run: brew install wget tree coreutils
      - name: Install package dependencies
        run: yarn
      - name: Build mobile dependencies
        run: yarn build --scope @celo/mobile --include-filtered-dependencies
      - name: Run E2E tests
        run: |
          cd packages/mobile
          yarn run test:e2e:ios -w 1
